apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-crash-reporter-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crash-reporter-binding
subjects:
  - kind: ServiceAccount
    name: k8s-crash-reporter-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-crash-reporter
  labels:
    app: k8s-crash-reporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-crash-reporter
  template:
    metadata:
      labels:
        app: k8s-crash-reporter
    spec:
      serviceAccountName: k8s-crash-reporter-sa
      containers:
        - name: k8s-crash-reporter
          image: weland/k8s-crash-reporter:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: k8s-crash-reporter-secrets
                  key: token
            - name: CHAT_ID
              valueFrom:
                secretKeyRef:
                  name: k8s-crash-reporter-secrets
                  key: chatId